version: '3.7'
services:
  psql:
    container_name: easy_gpt_psql
    image: postgres:15.3-alpine
    env_file: .env
    ports:
      - 5432:5432/tcp
    volumes:
      - easy_gpt_psql_data:/var/lib/postgresql/data
volumes:
  easy_gpt_psql_data:
